
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 8;
  public static final int SUMA = 3;
  public static final int POR = 5;
  public static final int PTCOMA = 9;
  public static final int EOF = 0;
  public static final int EVALUAR = 2;
  public static final int NUMERO = 7;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RESTA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EVALUAR",
  "SUMA",
  "RESTA",
  "POR",
  "DIV",
  "NUMERO",
  "DECIMAL",
  "PTCOMA"
  };
}

